---
apiVersion: metrics.keptn.sh/v1
kind: AnalysisDefinition
metadata:
  name: demo-app-analysis
  namespace: demo-app-dev
spec:
  objectives:
  - analysisValueTemplateRef:
      name: request-duration
    keyObjective: false
    target:
      failure:
        greaterThan:
          fixedValue: 3
      warning:
        greaterThan:
          fixedValue: 2
    weight: 1
  totalScore:
    passPercentage: 60
    warningPercentage: 50
---
apiVersion: metrics.keptn.sh/v1
kind: AnalysisValueTemplate
metadata:
  name: request-duration
  namespace: demo-app-dev
spec:
  provider:
    name: prometheus
  query: "{{ printf "sum by (path) (rate(http_request_duration_seconds_sum{path='/'}[1m]) / rate(http_request_duration_seconds_count{path='/'}[1m]))" }}"    
