apiVersion: v1
kind: Service
metadata:
  name: demo-app-nodeport
  namespace: demo-app-dev
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
    nodePort: 30103
  selector:
    app: demo-app
    app.kubernetes.io/name: demo-app
    app.kubernetes.io/part-of: demo-app
  sessionAffinity: None
  type: NodePort
