apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: demo-app
  namespace: demo-app-dev
spec:
  selector:
    matchLabels:
      app: demo-app
  podMetricsEndpoints:
  - port: http
    interval: 5s
    scrapeTimeout: 4s
