---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: demo-app-dev
  namespace: demo-app-dev
spec:
  selector:
    matchLabels:
      app: demo-app                                                                                                                                                              │
  endpoints:
  - port: http
    interval: 5s
    scrapeTimeout: 4s