apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
    name: demo-app-monitor
    namespace: demo-app-dev
    labels:
      app: demo-app
spec:
    selector:
      matchLabels:
      app: demo-app
    endpoints:
    - port: 8080
      interval: 5s