apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: feature-flag-change
spec:
  rules:
    - name: match-feature-flag-change
      match:
        any:
        # AND across kinds and namespaceSelector
        - resources:
            # OR inside list of kinds
            kinds:
            - FeatureFlag
            operations:
            - UPDATE
            selector:
              matchLabels:
                app: sample-app
                type: feature-flag
      generate:
        apiVersion: batch/v1
        kind: Job
        name: demo-app-load-test-{{request.object.metadata.resourceVersion}}
        # generate the resource in the new namespace
        namespace: "demo-app-dev"
        data:
          spec:
            template:
              metadata:
                labels:
                  app.kubernetes.io/instance: demo-app-dev
                  trigger-keptn-analysis: "true"
              spec:
                containers:
                - command:
                  - k6
                  - run
                  - https://raw.githubusercontent.com/heckelmann/kyverno-keptn-workshop/main/functions/load.js
                  image: grafana/k6:0.45.0
                  imagePullPolicy: IfNotPresent
                  name: load-test
                restartPolicy: OnFailure
            ttlSecondsAfterFinished: 300          


               