apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: keptn-analysis
spec:
  validationFailureAction: Audit
  rules:
    - name: keptn-analysis-success
      match:
        any:
        # AND across kinds and namespaceSelector
        - resources:
            # OR inside list of kinds
            kinds:
            - Analysis
            operations:
            - UPDATE
            selector:
              matchLabels:
                generate.kyverno.io/policy-name: feature-flag-change
      validate:
        message: "Analysis needs to be passed."
        pattern:
          status:
            pass: "true"