apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: load-test-completed
spec:
  rules:
    - name: load-test-completed
      match:
        all:
        # AND across kinds and namespaceSelector
        - resources:
            # OR inside list of kinds
            kinds:
            - Job/status
            operations:
            - UPDATE
            preconditions:
              any:
                - key: "{{ request.object.status.succeeded || `[]` }}"
                  operator: Equals
                  value: 1           
            selector:
              matchLabels:
                generate.kyverno.io/rule-name: match-feature-flag-change
      generate:
        apiVersion: metrics.keptn.sh/v1alpha3
        kind: Analysis
        name: service-analysis-kyverno
        # generate the resource in the new namespace
        namespace: "demo-app-dev"
        data:
          spec:
            timeframe:
              recent: 5m
            args:
              "workload": "demo-app-dev"
            analysisDefinition:
              name: demo-app-analysis            