apiVersion: batch/v1
kind: Job
metadata:
  labels:
    app.kubernetes.io/instance: demo-app-dev
  name: demo-app-load-test
  namespace: demo-app-dev
spec:
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: demo-app-dev
    spec:
      containers:
      - command:
        - k6
        - run
        - https://raw.githubusercontent.com/heckelmann/kyverno-keptn-workshop/main/functions/load.js
        image: grafana/k6:0.45.0
        imagePullPolicy: IfNotPresent
        name: load-test
      restartPolicy: OnFailure
  ttlSecondsAfterFinished: 300
status:
  succeeded: 1
