apiVersion: metrics.keptn.sh/v1alpha3
kind: Analysis
metadata:
  name: service-analysis-test
  namespace: demo-app-dev
spec:
  timeframe:
    recent: 5m
  args:
    "workload": "demo-app-dev"
  analysisDefinition:
    name: demo-app-analysis