apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-app-dev
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "10"  
spec:
  project: default
  source:
    repoURL: 'https://github.com/heckelmann/kyverno-keptn-workshop.git'
    path: "gitops/dev/demo-app"
    targetRevision: main
    helm:
      parameters:
        - name: "commitID" 
          value: "$ARGOCD_APP_REVISION"
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: demo-app-dev
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/template/metadata/labels/app.kubernetes.io~1version
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true