apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  name: flagd
  namespace: argocd
spec:
  source:
    repoURL: 'https://github.com/heckelmann/kyverno-keptn-workshop.git'
    targetRevision: main
    path: "gitops/infrastructure/flagd"
  destination:
    namespace: flagd
    server: 'https://kubernetes.default.svc'
  project: default
  syncPolicy:
    retry:
      limit: 5
      backoff:
        duration: 5s
        maxDuration: 3m0s
        factor: 2
    syncOptions:
      - CreateNamespace=true