apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  name: policy-reporter
  namespace: argocd
spec:
  sources:
    - repoURL: 'https://kyverno.github.io/policy-reporter'
      targetRevision: 2.23.1
      chart: policy-reporter
      helm:
        parameters:
          - name: "kyvernoPlugin.enabled"
            value: "true"     
          - name:  "ui.enabled"
            value: "true"
          - name: "ui.plugins.kyverno"
            value: "true"
  destination:
    namespace: policy-reporter
    server: 'https://kubernetes.default.svc'
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 5
      backoff:
        duration: 5s
        maxDuration: 3m0s
        factor: 2
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      