apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  name: kyverno
  namespace: argocd
spec:
  ignoreDifferences:
  - group: rbac.authorization.k8s.io/v1
    kind: ClusterRole
    jsonPointers:
    - /rules
  source:
    repoURL: 'https://kyverno.github.io/kyverno'
    targetRevision: 3.1.4
    chart: kyverno
  destination:
    namespace: kyverno
    server: 'https://kubernetes.default.svc'
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 5
      backoff:
        duration: 5s
        maxDuration: 3m0s
        factor: 2
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true
      - ServerSideApply=true
      