---
apiVersion: metrics.keptn.sh/v1
kind: AnalysisDefinition
metadata:
  name: demo-app-analysis
  namespace: demo-app-prod
spec:
  objectives:
  - analysisValueTemplateRef:
      name: request-duration
    target:
      failure:
        greaterThan:
          fixedValue: 3
      warning:
        greaterThan:
          fixedValue: 2
    weight: 1
    keyObjective: true
  totalScore:
    passPercentage: 90
    warningPercentage: 75
---
apiVersion: metrics.keptn.sh/v1
kind: AnalysisValueTemplate
metadata:
  name: request-duration
  namespace: demo-app-prod
spec:
  provider:
    name: prometheus
  query: "{{ printf "sum by (path) (rate(http_request_duration_seconds_sum{namespace='demo-app-prod', path='/'}[1m]) / rate(http_request_duration_seconds_count{path='/'}[1m]))" }}"    
