apiVersion: metrics.keptn.sh/v1alpha3
kind: Analysis
name: service-analysis-kyverno-{{request.object.metadata.resourceVersion}}
namespace: "demo-app-prod"
spec:
  timeframe:
    recent: 1m
  args:
    "workload": "demo-app-prod"
  analysisDefinition:
    name: demo-app-analysis            