apiVersion: apps/v1
kind: Deployment
metadata:
  name: flagd
  namespace: flagd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flagd
  template:
    metadata:
      labels:
        app: flagd
    spec:
      containers:
        - name: flagd
          image: ghcr.io/open-feature/flagd:latest
          ports:
            - containerPort: 8013
          resources:
            limits:
              cpu: "0.5"
              memory: "128Mi"
            requests:
              cpu: "0.1"
              memory: "50Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: flagd
  namespace: flagd
spec:
  selector:
    app: flagd
  ports:
    - protocol: TCP
      port: 8013
      targetPort: 8013

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: flagd
  namespace: flagd

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: flagd
rules:
  - apiGroups: [""]
    resources: ["*"]
    verbs: ["*"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: flagd-cluster-admin-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: flagd
    namespace: flagd