apiVersion: core.openfeature.dev/v1beta1
kind: FeatureFlag
metadata:
  name: feature-flags
  labels:
    app: sample-app
spec:
  flagSpec:
    flags:
      my-new-feature:
        state: ENABLED
        variants:
          'on': true
          'off': false
        defaultVariant: 'on'
