apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kyverno-keptn-workshop
  namespace: argocd
spec:
  source:
    path: charts/applications
    repoURL: {{ .Values.repo.url }}
    targetRevision: {{ .Values.repo.revision }}
    helm:
      values: |
        repo:
          url: {{ .Values.repo.url }}
          revision: {{ .Values.repo.revision }}
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 5
      backoff:
        duration: 5s
        maxDuration: 3m0s
        factor: 2
