apiVersion: metrics.keptn.sh/v1
kind: AnalysisDefinition
metadata:
  name: demo-app-analysis
  namespace: demo-app-prod
spec:
  objectives:
  - analysisValueTemplateRef:
      name: request-duration
    keyObjective: true
    target:
      failure:
        greaterThan:
          fixedValue: 3
      warning:
        greaterThan:
          fixedValue: 2
    weight: 1
  totalScore:
    passPercentage: 90
    warningPercentage: 75
